// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7VX8FSIFq7fYfLvJtYF2pxpXSK3X2xcw',
    appId: '1:577134548945:web:995ad1570e802ba3d3f2f0',
    messagingSenderId: '577134548945',
    projectId: 'jobfinder-e3133',
    authDomain: 'jobfinder-e3133.firebaseapp.com',
    storageBucket: 'jobfinder-e3133.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARpbp2dDpUkRcm8e2mxPjdI7IM85J6ePk',
    appId: '1:577134548945:android:23346ba6d9d3a99cd3f2f0',
    messagingSenderId: '577134548945',
    projectId: 'jobfinder-e3133',
    storageBucket: 'jobfinder-e3133.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOOyD0JuE-goTugaQGmDAH7tmTZNxxHq4',
    appId: '1:577134548945:ios:9aa1fd0913895b89d3f2f0',
    messagingSenderId: '577134548945',
    projectId: 'jobfinder-e3133',
    storageBucket: 'jobfinder-e3133.appspot.com',
    iosBundleId: 'com.example.jobfinderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOOyD0JuE-goTugaQGmDAH7tmTZNxxHq4',
    appId: '1:577134548945:ios:9aa1fd0913895b89d3f2f0',
    messagingSenderId: '577134548945',
    projectId: 'jobfinder-e3133',
    storageBucket: 'jobfinder-e3133.appspot.com',
    iosBundleId: 'com.example.jobfinderapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7VX8FSIFq7fYfLvJtYF2pxpXSK3X2xcw',
    appId: '1:577134548945:web:5488b127c082dd6fd3f2f0',
    messagingSenderId: '577134548945',
    projectId: 'jobfinder-e3133',
    authDomain: 'jobfinder-e3133.firebaseapp.com',
    storageBucket: 'jobfinder-e3133.appspot.com',
  );
}
